language: go

dist: xenial
sudo: true

install:
  - ./install-hugo.sh
script:
  - hugo

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master