baseURL = "https://fabienleite.github.io"
languageCode = "en-us"
title = "Fabien Leite"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Fabien Leite"
logo = "/images/icon.png"
enableEmoji = true

[params]
  description ="A blog about Appsec and things"

    [params.author]
    name = "Fabien Leite"
    thumbnail = "/images/portrait.jpg"
    description = "Appsec engineer, defender of the developer in a secure future."

    [params.social]
    github = "fabienleite"
    linkedin = "fabien-leite"
    twitter = "FabienLeite"

    [params.index]
    picture = "/images/portrait.jpg"
    title = "Fabien Leite"
    subtitle = "Appsec and stuff."
    mdtext = '''The idea of this blog is to talk about things I'm interested in. \
                I'm an application so it will probably mainly talk about Application Security but you can also expect\
                a few words about accessibility and other subjects.'''
    alertbar = true

[[menu.main]]
    name = "Blog"
    weight = 120
    identifier = "blog"
    url = "/blog/"