steps:
  - uses: actions/checkout@main
    with:
      submodules: true

  - uses: jsumners/gh-action-hugo-deploy@v1.0.0
    with:
      destination_repo: fabienleite/fabienleite.github.io
      destination_token: ${{ secrets.Deploy_Token }}